"DbUser" = "postgres"
"DbPassword" = "changeme"
"DbName" = "postgresDatabase"
"DbPort" = "5432"
"DbHost" = "terraform-20220730054342397100000001.conl2ah1tfe3.ap-southeast-2.rds.amazonaws.com"
"ListenHost" = "0.0.0.0"
"ListenPort" = "3000"